### ISSUE TITLE
Has SDK version 1.0.9 been released yet?

### ISSUE THREAD

**Issue by yumaishida** [awslabs/aws-appflow-custom-connector-java#62]
Looking at ChangeLog.md and the Example project, it looks like 1.0.9 has already been released, but in reality I don't think 1.0.9 is available yet.
Has version 1.0.9 been released yet?

**Comment by aaronsven** [comment]
Looking into

**Comment by yumaishida** [comment]
Thank you.

I don't really need to use 1.0.9 (I will use 1.0.8).

I have started implementing a custom connector for AppFlow as a new feature of my low-code development platform (not SaaS). I tried to use 1.0.9 because I thought 1.0.9 was the latest version according to the change logs and examples, but I could not get the jar from the Maven Central Repository, hence my question.
